repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'  # Use the latest stable version
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.1"]
        language_version: python3.10
        stages: [ push ]

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
        stages: [ push ]
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
      - id: djcss
        entry: djcss --tabwidth 2
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
        # Run this hook only on SCSS files (CSS and SCSS is the default)
        types: [ scss ]
        stages: [ push ]
      - id: djjs
        # Exclude JavaScript files in vendor directories
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
        stages: [ push ]
