# Generated by Django 5.0.6 on 2024-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="time",
            field=models.IntegerField(default=0),
        ),
    ]
