# Generated by Django 5.0.6 on 2024-07-09 17:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0004_alter_todoitem_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="created_at",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
