# Generated by Django 5.0.6 on 2024-07-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0005_todoitem_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="label",
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="time",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="datetime",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="describtion",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="todoitem",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
