# Generated by Django 5.0.6 on 2024-07-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0006_remove_todoitem_label_remove_todoitem_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="describtion",
            new_name="description",
        ),
    ]
