# Generated by Django 5.0.6 on 2024-07-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0007_rename_describtion_todoitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
